### ISSUE TITLE
Using TM_SELECTED_TEXT with a tab does not work as expected

### ISSUE THREAD

**Issue by svermeulen** [hrsh7th/vim-vsnip#86] opened 2020-08-09 00:34 UTC
For example:
```json
  "For Each": {
    "prefix": ["fe"],
    "body": [
      "for ${2:item} in *${1:iterable}",
      "\t${TM_SELECTED_TEXT}"
    ]
  },
```
Using the above snippet, if I then select multiple lines, then trigger the `vsnip-cut-text` map, only the first line is indented

**Comment by hrsh7th** [comment] 2020-08-09 07:10
I didn't found the approach to detect indentation at the snippet expansion.

I will consider it... (and I investigate VSCode behavior)

**Comment by mg979** [comment] 2020-08-12 02:45
I tried to fix this in #92 but placeholders must be updated you can see here (first without, then with my bad PR):

[![asciicast](https://asciinema.org/a/ivQUx2oVApCxKGU5O8dy2GR6I.svg)](https://asciinema.org/a/ivQUx2oVApCxKGU5O8dy2GR6I)

**Comment by hrsh7th** [comment] 2020-08-12 02:52
VSCode does fix the indentation at the TM_SElECTED_TEXT resolving.

I planning to solve via the same approach.

We should provide the detailed context for variable resolver for it.

**Comment by mg979** [comment] 2020-08-12 03:01
The problem I saw is that the variable is resolved when snippet is started, that is at the first line, not where the selected text will be inserted, so `indent(line('.'))` returns a wrong value. I could not detect the right indentation when the variable is resolved.

**Comment by hrsh7th** [comment] 2020-08-12 03:06
Currently, My thoughts are the below.

```viml
function! s:TM_SELECTED_TEXT(context) abort
  let l:selected_text = vsnip#selected_text()
  if empty(l:selected_text)
    return v:null
  endif
  return %SOLVE_INDENT%(a:context.before_text, l:selected_text)
endfunction
call vsnip#variable#register('TM_SELECTED_TEXT', function('s:TM_SELECTED_TEXT'))
```

This is using `a:context.before_text` instead of physical buffer text so we can detect indentation.

But I want to use the text that applied `s:Snippet.sync`, I'm considering it.

**Comment by hrsh7th** [comment] 2020-08-12 03:17
Wait, you are correct.

If snippet(`    $TM_SELECTED_TEXT    `) will expanded at the cursor on `_____|_____`, we will detect the indentation wrongly maybe...

**Comment by mg979** [comment] 2020-08-12 03:18
I think: the inserted text can't contain placeholders, so you could get the number of lines that have been inserted, with the starting line of the insertion, reindent those, and update the placeholders that come in that line.

To get the right indent, you don't need the context before it (what does the plugin know about the right indent?), you need the indentation of the line where the insertion happen. So for example, if the snippet line is

    "\t${TM_SELECTED_TEXT}"

and the indentation is 1 tab at the insertion point, 1 tab must be added to all lines. And so on. I think.

**Comment by hrsh7th** [comment] 2020-08-12 03:26
vsnip does not update placeholder position&range manually but always calculate from AST.

So if we fix the indentation of `$TM_SELECTED_TEXT`-node value, the other node position&range update automatically.

VSCode seems to uses `\n\zs\t*` as the indentation fixing, it can be detect from AST before snippet insertion.

https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/snippetVariables.ts#L85

**Comment by mg979** [comment] 2020-08-12 03:34
But the exact line where the variable is resolved is needed.

Also, if there is a `\t` before `TM_SELECTED_TEXT`, vim generally indents the line on its own (for example after `for`, `if`, ...), so you have double indentation for that line, and it shouldn't be.

So I think it's better to reindent the inserted lines with `normal! ==` when an insertion happens, for `n` lines of the insertion. But then how do you update placeholders?

**Comment by hrsh7th** [comment] 2020-08-12 03:47
@mg979 `normal! ==` is reasonable but vsnip can't use that approach... (it is the limitation by design)

the vsnip's design is explained as below.

### Insert snippet
1. Create AST from snippet body and fix it (sync, resolve, reindent etc)
2. Insert fixed snippet body to physical buffer

### Follow text_changes
1. Listen every `on_text_changed`
2. Detect the diff of the `this change` (it does not detect the diff wisely for performance, always detects the `one` diff.)
3. Apply the diff to the AST.
4. Fix snippet (sync, resolve, reindent etc...) and then write-back to the buffer when snippet AST needs some other changes.

`normal! ==` makes the diff at wide-range it has a possibility to contain multiple placeholders so the approach will break the snippet ast.

**Comment by mg979** [comment] 2020-08-12 04:08
So you want to calculate indentation manually, and modify the inserted text? You also have to replace the leading `\t` with the real indent of the line where the text is inserted, or the first line is overindented.

Anyway I think the variable is resolved too early, currently, to get the right indent of its starting line. Or not?

**Comment by hrsh7th** [comment] 2020-08-12 13:10
Yes, I'm worried too, probably we can't detect indentation correctly on the timing of the variable resolving.

But VSCode seems to solve it on a similar timing... so anyway, I try it as WIP.

**Comment by mg979** [comment] 2020-08-12 14:16
You could do it in multiple steps:

- expand snippet, but:
  - don't expand `$TM_SELECTED_TEXT`
  - the function `TM_SELECTED_TEXT()` increases a counter, but returns `$TM_SELECTED_TEXT`
- process snippet adding placeholders as usual
- if `counter` isn't zero:
  - search for the next `$TM_SELECTED_TEXT`
  - get current indent
  - replace `$TM_SELECTED_TEXT` with the selected text (there can be multiple replacements...)
  - reindent all lines that have been added
  - get indent again
- then update placeholders, but only those in the same line of `$TM_SELECTED_TEXT`, with the difference of indentation:
  - before `TM_SELECTED_TEXT`, at line of insertion
  - after  `TM_SELECTED_TEXT`, at last line after insertion (the same line if selected text is not multiline)
- repeat as long as `count` isn't zero

**Comment by mg979** [comment] 2020-08-12 14:26
> But VSCode seems to solve it on a similar timing...

I see it uses `this._selection.positionLineNumber` so it must pass the actual position of the variable in the buffer after snippet expansion, something you aren't doing and that it's needed to get the right indent of the line where text is inserted.

**Comment by hrsh7th** [comment] 2020-08-12 15:01
I think VSCode does `resolveVariables` on https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/snippetSession.ts#L493 

It's called before the snippet expansion so we don't need to wait for the snippet expansion for variable resolving, I think.

I think #101 seems to work as expected mostly but it has a bug a little yet.

**Comment by hrsh7th** [comment] 2020-08-12 15:22
I have solved a bug of the PR.
I think the problem could be solved by this PR.

_But the PR's implementation is bit ugly so I will organize implementation..._

**Comment by hrsh7th** [comment] 2020-08-12 15:37
Probably, I was missing the https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/snippetVariables.ts#L104

I consider how to implement it in vsnip.

**Comment by mg979** [comment] 2020-08-12 15:40
What is the problem? Indentation of first line?

**Comment by hrsh7th** [comment] 2020-08-12 16:51
Yes, Currently implementation seems to have a bug of the indented one line selection.

I think we should carefully consider it.

1. `$TM_SELECTED_TEXT` or `["<div>", "\t$TM_SELECTED_TEXT", "</div>"]`
2. single indented line selection or multiple indented line selection
3. char-wise single line selection or char-wise multiple line selection

I will write integration tests for it that will be helpful to understand the behavior.

**Comment by mg979** [comment] 2020-08-12 17:00
The thing is that vim already indents code as you type, so the first leading `\t` in snippet body is too much. The following lines need the full resolved indent, because vim won't touch them. If the problem is for first line, one should remove (for first line only) the whole leading `\s*` before `$TM_SELECTED_TEXT`.

**Comment by hrsh7th** [comment] 2020-08-12 17:15
The demo of current PR is here.

![Kapture 2020-08-13 at 2 10 38](https://user-images.githubusercontent.com/629908/90045792-850f3800-dd0a-11ea-9060-8ce8888452fa.gif)

Most cases work as expected.
But the last case does not work as expected to me.

**Closed** 2020-08-13 13:43 UTC
Labels: difficulty:high, enhancement

**Comment by svermeulen** [comment] 2020-08-13 16:38
Can confirm this fixes the issue for me. :). Thanks

**Comment by hrsh7th** [comment] 2020-08-13 16:42
Thank you for confirmation.
It's very useful!
