### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by sigzero** [hrsh7th/vim-vsnip#76] opened 2020-08-05 14:15 UTC
I get the Lua error when I try to do anything with vsnips. I have the latest vsnips installed.

The two screenshots show the error and my vim version. I only have the following defined in my vimrc:

`let g:vsnip_snippet_dir = expand('C:/Vim/vimfiles/vsnip')`
`imap <expr> <S-Tab> vsnip#available(-1) ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'`
`smap <expr> <S-Tab> vsnip#available(-1) ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'`
`imap <expr> <Tab>   vsnip#available()   ? '<Plug>(vsnip-expand-or-jump)' : '<Tab>'`
`smap <expr> <Tab>   vsnip#available()   ? '<Plug>(vsnip-expand-or-jump)' : '<Tab>'`
![vim_version](https://user-images.githubusercontent.com/540937/89423364-65718180-d704-11ea-917f-080c70125fb8.png)
![vsnips_error](https://user-images.githubusercontent.com/540937/89423366-660a1800-d704-11ea-9478-42816f7e6d3e.png)

**Comment by hrsh7th** [comment] 2020-08-05 15:00
Thank you for your report!

I can't understand the cause of it now.

Currently, vsnip uses `vim-vital-vs` module it using Lua in only a neovim environment.

https://github.com/hrsh7th/vim-vsnip/blob/master/autoload/vital/_vsnip/VS/Text/Diff.vim#L143

I guess the error can be avoidable when we use `Lua` command in function context...?

I will try it soon.

**Comment by hrsh7th** [comment] 2020-08-05 15:06
@sigzero Sorry, I think it should be fixed now by https://github.com/hrsh7th/vim-vsnip/commit/feed7b4733085ce6b2ef9c5d8d8c886c9ef0edf1 .

Could you try it? (I have no environment to reproduce it... sorry...)

**Comment by sigzero** [comment] 2020-08-05 15:09
Tested and it is fixed.

**Closed** 2020-08-05 15:09 UTC
Labels: bug

**Comment by hrsh7th** [comment] 2020-08-05 15:10
Thank you for the investigation!
